#!/bin/sh

# Delete plugins that fucks it up, and are not needed in QA

for f in  dirtysuds-embed-pdf lockdown-wp-admin uber-media
do
echo "Deleting wp-content/plugins/$f"
rm -R wp-content/plugins/$f
done
